# Utiliser une image de base existante
FROM python:3.9

# Se déplacer dans le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet dans l'image Docker
COPY . /app

# Installer les dépendances du projet
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    ffmpeg libsm6 libxext6 \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*


# Copiez le code de l'application Dash 2 dans le conteneur
COPY app2 app2


# Installez les dépendances
RUN pip install --no-cache-dir -r app2/requirements.txt 


# Définir les variables d'environnement pour chaque application
ENV APP2_PORT=8888

# Exposez les ports des deux applications
EXPOSE $APP2_PORT

# Commande pour exécuter le script de démarrage
CMD ["python", "-m", "/app/app2/clusters.py", "--port" "$APP2_PORT"]

HEALTHCHECK CMD curl --fail http://localhost:$APP2_PORT/_stcore/health
